# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
description = "AEM Asset Search Edge Function"
language = "javascript"
manifest_version = 3
name = "aem-asset-search"
service_id = ""

[scripts]
  build = "npm run build:edge"
  post_init = "npm install"

[local_server]
  [local_server.backends]
    [local_server.backends.aem-publish]
      url = "https://publish-p63260-e524717.adobeaemcloud.com"

  [local_server.config_stores]
    [local_server.config_stores.config_default]
      format = "inline-toml"
    [local_server.config_stores.config_default.contents]
      LOG_LEVEL = "DEBUG"
      AEM_PUBLISH_HOST = "publish-p63260-e524717.adobeaemcloud.com"
      DAM_ROOT_PATH = "/content/dam/asset-share-commons/en/public"
