kind: "EdgeFunctions"
version: "1"
data:
  services:
    - name: asset-search
  configs:
    - key: LOG_LEVEL
      value: DEBUG
    - key: AEM_PUBLISH_HOST
      value: publish-p63260-e524717.adobeaemcloud.com
    - key: DAM_ROOT_PATH
      value: /content/dam/asset-share-commons/en/public
